linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - style
      - diagnostic
      - performance
    disabled-checks:
      - captLocal
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/fpmi-hci-2023
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  lll:
    line-length: 180
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  skip-dirs:
    - vendor
    - docs
    - test

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: (.+)_test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
