{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample.name" . }}-config
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
data:
{{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}