{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample.name" . }}-secret
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
{{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}