name: Build - Manual

on:
  workflow_dispatch: # manual trigger
permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  codeql:
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/codeql.yaml@main"
  lint:
    needs: codeql
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/golangci_lint.yaml@main"
    secrets:
      gh_sudo_token: ${{ secrets.GH_SUDO_TOKEN }}
  build_and_push:
    needs: lint
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/docker_build_and_publish.yaml@main"
    with:
      name: sampleservice
    secrets:
      gh_sudo_token: ${{ secrets.GH_SUDO_TOKEN }}
