name: Build - Pull Request

on:
  pull_request:
permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  codeql:
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/codeql.yaml@main"
  lint:
    needs: codeql
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/golangci_lint.yaml@main"
    secrets:
      gh_sudo_token: ${{ secrets.GH_SUDO_TOKEN }}
  build:
    needs: lint
    uses: "fpmi-hci-2023/project13b-chatgpt/.github/workflows/docker_build.yaml@main"
    secrets:
      gh_sudo_token: ${{ secrets.GH_SUDO_TOKEN }}
