name: "Push Helm Chart to GHCR"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Git Fetch
        if: steps.build_src.outputs.run_build == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.build_src.outputs.git_ref }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.kubernetes_url }}
          k8s-secret: ${{ secrets.kubernetes_secret }}
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.6.0'
      - name: Add Helm Repo
        run: helm repo add stable https://charts.helm.sh/stable
      - name: Update Helm Repo
        run: helm repo update
      - name: Package Helm Chart
        run: helm package ./charts/sample
      - name: Publish Helm Chart
        run: |
          helm repo add hci-pr13b ghcr.io/${{ github.repository_owner }}/hci-pr13b
          helm repo update
          helm push --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} ./charts hci-pr13b
